name: vacmap_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numba=0.63.1
  - numpy=2.2.6
  - edlib=1.3.9
  - biopython=1.86
  - pandas=2.3.3
  - pysam=0.23.3
  - python=3.10.17
  - samtools=1.23
  - setuptools=67.6.1
  - zlib=1.3.1
  - cigar=0.1.3
  - matplotlib=3.10
  - minimap2=2.29
  - pip=25.3
  - psutil=7.2.1
  - pip:
      - vacmap-index==0.0.3

