name: vacmap_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numba
  - numpy
  - edlib
  - biopython
  - pandas
  - pysam
  - python=3.10.17
  - samtools=1.23
  - setuptools=67.6.1
  - zlib
  - cigar
  - matplotlib
  - minimap2==2.29
  - pip
  - psutil
  - pip:
      - vacmap-index==0.0.2

